import { Product } from "@/types";

export const products: Product[] = [
  {
    id: "1",
    title: "Sony WH-1000XM5 Wireless Noise Canceling Headphones",
    description: "Industry-leading noise cancellation, 30-hour battery life, and crystal-clear hands-free calling. Ultra-comfortable lightweight design.",
    price: 348.00,
    originalPrice: 399.99,
    rating: 4.8,
    reviews: 12450,
    image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?q=80&w=1000&auto=format&fit=crop",
    category: "Electronics",
    isPrime: true,
    inStock: true,
  },
  {
    id: "2",
    title: "Apple MacBook Air 15-inch Laptop - M2 Chip",
    description: "Supercharged by M2. 8GB Unified Memory, 256GB SSD Storage. Liquid Retina Display. Works with iPhone/iPad.",
    price: 1199.00,
    originalPrice: 1299.00,
    rating: 4.9,
    reviews: 850,
    image: "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=1000&auto=format&fit=crop",
    category: "Computers",
    isPrime: true,
    inStock: true,
  },
  {
    id: "3",
    title: "Logitech MX Master 3S - Performance Wireless Mouse",
    description: "Ultra-fast scrolling, Ergo design, 8K DPI Any-Surface Tracking, Quiet Clicks, USB-C, Bluetooth, Windows & Mac.",
    price: 99.99,
    rating: 4.7,
    reviews: 21300,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=1000&auto=format&fit=crop",
    category: "Accessories",
    isPrime: true,
    inStock: true,
  },
  {
    id: "4",
    title: "Keurig K-Elite Coffee Maker, Single Serve K-Cup Pod Brewer",
    description: "Brushed Slate. Strong Brew button, Iced Coffee setting, and 75oz water reservoir.",
    price: 119.00,
    originalPrice: 189.99,
    rating: 4.6,
    reviews: 5400,
    image: "https://images.unsplash.com/photo-1520981825232-ece5fae45120?q=80&w=1000&auto=format&fit=crop",
    category: "Home",
    isPrime: false,
    inStock: true,
  },
  {
    id: "5",
    title: "PlayStation 5 Console (PS5) - Slim Edition",
    description: "Experience lightning-fast loading with an ultra-high-speed SSD, deeper immersion with haptic feedback, and 3D Audio.",
    price: 499.99,
    rating: 4.9,
    reviews: 32000,
    image: "https://images.unsplash.com/photo-1606318801954-d46d46d3360a?q=80&w=1000&auto=format&fit=crop", 
    category: "Gaming",
    isPrime: true,
    inStock: false,
  },
  {
    id: "6",
    title: "Herman Miller Aeron Ergonomic Chair - Size B",
    description: "The benchmark for ergonomic seating. Graphite color. Fully adjustable arms and lumbar support.",
    price: 1250.00,
    rating: 4.5,
    reviews: 890,
    image: "https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?q=80&w=1000&auto=format&fit=crop",
    category: "Furniture",
    isPrime: false,
    inStock: true,
  },
];